spring.application.name=eventbooking

# Format: ${ENV_VARIABLE_NAME:fallback_value}
# Locally: ENV_VARIABLE_NAME doesn't exist -> uses fallback (localhost MySQL)
# On Railway: Railway sets these env variables automatically -> uses Railway's values

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/eventbooking}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ddl-auto=update -> Hibernate creates/updates tables automatically on whichever
# database it connects to (local or Railway) based on our @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Railway sets a PORT environment variable telling your app which port to run on;
# locally it falls back to 8080 as always.
server.port=${PORT:8080}